### ISSUE TITLE
Not sure how to use this lib correctly

### ISSUE THREAD

**Issue by kristianmandrup** [BadgeLabs/mocha-eslint#48]
Trying to figure out a way to lint my test files, currently co-located with the src code.
Examples I have seen so far reference an index file in src and one in test, but I don't see why I should manually link my test files together in order to lint them!!

I found this article, on the right track? 

https://robots.thoughtbot.com/testing-your-style-with-eslint-and-mocha

but this setup looks very cumbersome and complicated... why I was happy to find this lib: `mocha-lint`

I put my `mocha-lint.js` file as described in your Readme in the root of my project. Trying to run it simply via `node`. 

Should I instead run the file with `mocha`? should I put it in my `test` or `src` folder?
How do I make it pick up my `.eslintrc` rules?

Not very clear... please advice! Thanks :)

```
$ node mocha-lint.js 
/Users/kristianmandrup/repos/node-libs/code-operator/node_modules/mocha-eslint/index.js:53
  describe('eslint', function () {
  ^

ReferenceError: describe is not defined
    at module.exports (/Users/kristianmandrup/repos/node-libs/code-operator/node_modules/mocha-eslint/index.js:53:3)
    at Object.<anonymous> (/Users/kristianmandrup/repos/node-libs/code-operator/mocha-lint.js:27:1)
```

**Comment by IanVS** [comment]
If you want to lint your test files, you do not need this or any other library, ESLint alone is sufficient.  This library is intended to run your linting _as_ a test.

If you have a specific way of naming your test files, (e.g. `src/component.spec.js`), then you can run eslint like: `eslint src/**/*.spec.js`.  Does that help?

**Comment by kristianmandrup** [comment]
Hey, sorry. Just been banging my head! I realize that your lib is possibly for turning the eslint errors into regular mocha errors?

I'm trying to follow the thread here https://github.com/eslint/eslint/issues/3611

Can I do this in my npm scripts? Note that I'm co-locating tests with code, to avoid deeply nested refs.

My test files are of the form `*.test.js`

```
    "mocha:test": "mocha-webpack \"src/{**/,/}*.test.js\"",
    "test": "npm run mocha:test",
    "test:watch": "npm run test -- --watch",

    ...
    "lint": "eslint src/**/*.js",
    "lint:fix": "npm run lint --fix",
```

I'd like to run lint before each mocha test, including when I'm watching for file changes... 
but efficiently (using some kind of caching!?)

Thanks!

**Comment by IanVS** [comment]
>I realize that your lib is possibly for turning the eslint errors into regular mocha errors?

Yep, exactly.

You can probably set up what you want, but it will be non-trivial.  I'm not sure how mocha watch works exactly, but I think it's not going to give you the flexibility to run linting on each file change.  It seems that you may also be using webpack, however?  If so, you can set up [`eslint-loader`](https://github.com/MoOx/eslint-loader) as a pre-loader in your webpack config.  Then, the test files will be  linted before they are run, and on any changes only the changed files will be linted.  I think that's what you're looking for, and is in fact what I use currently as well.  

One other small point, your `test:watch` script above should probably be `"npm run mocha:test -- --watch"`, because the way you have it now, the `--watch` will not flow through the `test` script to `mocha:test`.

If you want any further help setting all this up, I'd suggest jumping into the ESLint [gitter chat](https://gitter.im/eslint/eslint) and @-mentioning me there if you like.

**Comment by kristianmandrup** [comment]
Thanks :) Btw, do you know the possible reason behind this issue:

https://github.com/zinserjan/mocha-webpack/issues/63

```
  0 passing (5ms)
  1 failing
  1) Operator: code an instance have a name:
     TypeError: (0 , _chai.expect)(...).to.be is not a function
      at Context.that.should (.tmp/mocha-webpack/1125819f4470d55ab4c318bd8d350078/1125819f4470d55ab4c318bd8d350078-output.js:140:3
```
